{"uid":"effa30efe1355d78","name":"test_TC_003_user_can_autorize[locked_out_user-secret_sauce]","fullName":"tests.test_TC_003_user_can_be_autorize.TestSample#test_TC_003_user_can_autorize","historyId":"4fde3e06ba7cfe1efb59ebf7e0eb76e1","time":{"start":1671194975154,"stop":1671194975429,"duration":275},"status":"skipped","statusMessage":"XFAIL\n\nAssertionError: Expected link inventory not found in URL https://www.saucedemo.com/","statusTrace":"self = <SauceDemoProject.tests.test_TC_003_user_can_be_autorize.TestSample object at 0x7ff0d7330c10>\nd = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1a5e38730e0d8ca605cf0556f91dce13\")>\nusername = 'locked_out_user', password = 'secret_sauce'\n\n    @pytest.mark.parametrize(\n        \"username, password\",\n        [\n            (\"standard_user\", \"secret_sauce\"),\n            (\"performance_glitch_user\", \"secret_sauce\"),\n            (\"problem_user\", \"secret_sauce\"),\n            pytest.param(\n                \"locked_out_user\",\n                \"secret_sauce\",\n                marks=pytest.mark.xfail(raises=AssertionError),\n            ),\n        ],\n    )\n    def test_TC_003_user_can_autorize(self, d, username, password):\n        link = \"https://www.saucedemo.com/\"\n        page = LoginPage(d, link)\n        page.open_page()\n        page.register_user(username, password)\n        link = \"https://www.saucedemo.com/inventory.html\"\n        page = ProductsPage(d, link)\n>       page.should_be_products_page()\n\ntests/test_TC_003_user_can_be_autorize.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/products_page.py:16: in should_be_products_page\n    self.should_be_link(ProductsPageSrc.LINK)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.products_page.ProductsPage object at 0x7ff0d73e5810>\nlink = 'inventory'\n\n    def should_be_link(self, link):\n        \"\"\"Check that the link provided is in the current URL of the browser.\n    \n        Args:\n            link: link browser\n        \"\"\"\n        assert (\n>           link in self.browser.current_url\n        ), f\"Expected link {link} not found in URL {self.browser.current_url}\"\nE       AssertionError: Expected link inventory not found in URL https://www.saucedemo.com/\n\npages/base_page.py:350: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser","time":{"start":1671194967840,"stop":1671194967840,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"d","time":{"start":1671194967840,"stop":1671194968714,"duration":874},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"g","time":{"start":1671194968714,"stop":1671194968889,"duration":175},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL\n\nAssertionError: Expected link inventory not found in URL https://www.saucedemo.com/","statusTrace":"self = <SauceDemoProject.tests.test_TC_003_user_can_be_autorize.TestSample object at 0x7ff0d7330c10>\nd = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1a5e38730e0d8ca605cf0556f91dce13\")>\nusername = 'locked_out_user', password = 'secret_sauce'\n\n    @pytest.mark.parametrize(\n        \"username, password\",\n        [\n            (\"standard_user\", \"secret_sauce\"),\n            (\"performance_glitch_user\", \"secret_sauce\"),\n            (\"problem_user\", \"secret_sauce\"),\n            pytest.param(\n                \"locked_out_user\",\n                \"secret_sauce\",\n                marks=pytest.mark.xfail(raises=AssertionError),\n            ),\n        ],\n    )\n    def test_TC_003_user_can_autorize(self, d, username, password):\n        link = \"https://www.saucedemo.com/\"\n        page = LoginPage(d, link)\n        page.open_page()\n        page.register_user(username, password)\n        link = \"https://www.saucedemo.com/inventory.html\"\n        page = ProductsPage(d, link)\n>       page.should_be_products_page()\n\ntests/test_TC_003_user_can_be_autorize.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/products_page.py:16: in should_be_products_page\n    self.should_be_link(ProductsPageSrc.LINK)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.products_page.ProductsPage object at 0x7ff0d73e5810>\nlink = 'inventory'\n\n    def should_be_link(self, link):\n        \"\"\"Check that the link provided is in the current URL of the browser.\n    \n        Args:\n            link: link browser\n        \"\"\"\n        assert (\n>           link in self.browser.current_url\n        ), f\"Expected link {link} not found in URL {self.browser.current_url}\"\nE       AssertionError: Expected link inventory not found in URL https://www.saucedemo.com/\n\npages/base_page.py:350: AssertionError","steps":[],"attachments":[{"uid":"d58026c553516dee","name":"Screenshot","source":"d58026c553516dee.png","type":"image/png","size":69852},{"uid":"632e898062526972","name":"stdout","source":"632e898062526972.txt","type":"text/plain","size":33}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"g::0","time":{"start":1671194975977,"stop":1671194976092,"duration":115},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(raises=<class 'AssertionError'>)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_TC_003_user_can_be_autorize"},{"name":"subSuite","value":"TestSample"},{"name":"host","value":"fv-az360-669"},{"name":"thread","value":"2755-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_TC_003_user_can_be_autorize"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"password","value":"'secret_sauce'"},{"name":"username","value":"'locked_out_user'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"cc30357c158a4aec","reportUrl":"https://Natalia-Tsy.github.io/SauceDemoProject/285//#testresult/cc30357c158a4aec","status":"skipped","statusDetails":"XFAIL\n\nAssertionError: Expected link inventory not found in URL https://www.saucedemo.com/","time":{"start":1671194910666,"stop":1671194911049,"duration":383}}]},"tags":["@pytest.mark.xfail(raises=<class 'AssertionError'>)"]},"source":"effa30efe1355d78.json","parameterValues":["'secret_sauce'","'locked_out_user'"]}