{"name": "test_TC_003_user_сan_autorize[locked_out_user-secret_sauce]", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: wrong url", "trace": "self = <SauceDemoProject.tests.test_TC_003_user_can_be_autorize.TestSample object at 0x00000189ADE2B910>\nd = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"cc85bf719a05286725e612ffab5ef8cc\")>\nusername = 'locked_out_user', password = 'secret_sauce'\n\n    @pytest.mark.parametrize(\n        \"username, password\",\n        [\n            (\"standard_user\", \"secret_sauce\"),\n            (\"performance_glitch_user\", \"secret_sauce\"),\n            (\"problem_user\", \"secret_sauce\"),\n            pytest.param(\n                \"locked_out_user\",\n                \"secret_sauce\",\n                marks=pytest.mark.xfail(raises=AssertionError),\n            ),\n        ],\n    )\n    def test_TC_003_user_сan_autorize(self, d, username, password):\n        link = \"https://www.saucedemo.com/\"\n        page = LoginPage(d, link)\n        page.open_page()\n        page.register_user(username, password)\n        time.sleep(2)\n        link = \"https://www.saucedemo.com/inventory.html\"\n        page = ProductsPage(d, link)\n>       page.should_be_products_page()\n\ntest_TC_003_user_can_be_autorize.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\products_page.py:13: in should_be_products_page\n    self.should_be_link(ProductsPageSrc.LINK)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.products_page.ProductsPage object at 0x00000189ADE95F00>\nlink = 'inventory'\n\n    def should_be_link(self, link):\n>       assert link in self.browser.current_url, \"wrong url\"\nE       AssertionError: wrong url\n\n..\\pages\\base_page.py:59: AssertionError"}, "attachments": [{"name": "Screeshot", "source": "5357f8a3-14f0-45c4-ba05-7abeb11be462-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "d1975a0c-098c-470b-9228-1fc92db7b749-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1669801140644, "stop": 1669801142850, "uuid": "fdbec0b0-d005-4441-b5f3-4e08c55697e9", "historyId": "14fec9e14c2eabd56f61c502cf39b536", "testCaseId": "58098719add8c8f75a04510e5eb59a4a", "fullName": "tests.test_TC_003_user_can_be_autorize.TestSample#test_TC_003_user_сan_autorize", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(raises=<class 'AssertionError'>)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_TC_003_user_can_be_autorize"}, {"name": "subSuite", "value": "TestSample"}, {"name": "host", "value": "DESKTOP-DBCHJ8G"}, {"name": "thread", "value": "13448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_TC_003_user_can_be_autorize"}]}